Add color and external vars to setup scripts
* Add some color to make echos stand out
* Users of setup_{tmix,vim,zsh} can now pass `URL` as env variable to
  set custom repo
* Users of setup_aurutils can no pass `NAME` and `DIR` as env variable
  to set custom repo name and path

diff --git a/penguin-dev-tools/setup_aurutils b/penguin-dev-tools/setup_aurutils
--- a/penguin-dev-tools/setup_aurutils
+++ b/penguin-dev-tools/setup_aurutils
@@ -3,29 +3,33 @@
 # setup aurutils
 
 # repo name
-repo_name="custom"
+repo_name=${NAME:-"custom"}
 
 # path to repo
-repo_dir="$HOME/Packages"
+repo_dir=${DIR:-"$HOME/Packages"}
 
-echo "Setup aurutils repo..."
-echo "Name: $repo_name"
-echo "Path: $repo_dir"
+# color output (msg,info,err,reset)
+m='\033[1;35m'; i='\033[1;32m'; e='\033[1;31m'; n='\033[0m'
 
-read -s -k "?Press any key continue" && echo
+echo "${m}Setup aurutils repo...${n}"
+echo "${m}Name: ${i}$repo_name${n}"
+echo "${m}Path: ${i}$repo_dir${n}"
+echo "${i}"
+vared -cp "Confirm (y/n)? " ans
+[[ "$ans" =~ ^[Yy]$ ]] || exit 1
 
-echo " * Create repo directory"
+echo "${m} * Create repo directory${n}"
 mkdir -p $repo_dir &>/dev/null
 [[ $? -eq 0 ]] || \
-  { echo "failed to create repo path"; exit 1 }
+  { echo "${e}Failed to create repo path${n}"; exit 1 }
 
-echo " * Initialize package database..."
+echo "${m} * Initialize package database...${n}"
 cd $repo_dir
 repo-add -R $repo_name.db.tar
 [[ $? -eq 0 ]] || \
-  { echo "failed to create repo db"; exit 1 }
+  { echo "${e}Failed to create repo db${n}"; exit 1 }
 
-echo " * Update $USER's pacman.conf"
+echo "${m} * Update ${i}$USER${m}'s pacman.conf${n}"
 local_temp="$(mktemp)"
 local_conf="$HOME/.pacman.conf"
 cp $local_conf $local_temp &>/dev/null
@@ -34,17 +38,17 @@ echo "SigLevel = Optional TrustAll" >> $local_temp
 echo "Server = file://$repo_dir" >> $local_temp
 cp -b $local_temp $local_conf -S .backup
 
-echo " * Update system pacman.conf"
+echo "${m} * Update system pacman.conf${n}"
 sys_temp="$(mktemp)"
 sys_conf="/etc/pacman.conf"
 cp -p $sys_conf $sys_temp
 echo "\nInclude = $HOME/.pacman.conf" >> $sys_temp
 sudo cp -pb $sys_temp $sys_conf -S .backup
 
-echo " * Sync pacman db"
+echo "${m} * Sync pacman db${n}"
 sudo pacman -Sy
 
-echo "Done!"
+echo "${i}Done${n}"
 exit 0
 
 # vim: ft=zsh ts=2 sw=2 et:
diff --git a/penguin-dev-tools/setup_tmux b/penguin-dev-tools/setup_tmux
--- a/penguin-dev-tools/setup_tmux
+++ b/penguin-dev-tools/setup_tmux
@@ -3,7 +3,7 @@
 # setup tmux
 
 # source
-src_url="https://git.linuxit.us/spider/tmux"
+src_url=${URL:-"https://git.linuxit.us/spider/tmux"}
 
 # install to
 dest_dir="$HOME/.tmux"
@@ -11,23 +11,27 @@ dest_dir="$HOME/.tmux"
 # plugins
 plugin_lst="$dest_dir/plugins.txt"
 
-echo "Installing tmux setup..."
-echo "Source: $src_url"
-echo "Target: $dest_dir"
+# color output (msg,info,err,reset)
+m='\033[1;35m'; i='\033[1;32m'; e='\033[1;31m'; n='\033[0m'
 
-read -s -k "?Press any key continue" && echo
+echo "${m}Installing tmux setup...${n}"
+echo "${m}Source: ${i}$src_url${n}"
+echo "${m}Target: ${i}$dest_dir${n}"
+echo "${i}"
+vared -cp "Confirm (y/n)? " ans
+[[ "$ans" =~ ^[Yy]$ ]] || exit 1
 
 # clone repo
 if test -d $dest_dir
 then
-  echo "Target '$dest_dir' already exists!"
+  echo "${m}Target '${i}$dest_dir${m}' already exists!${n}"
   exit 1
 else
   if git clone $src_url $dest_dir
   then
-    echo "Cloned repo to $dest_dir"
+    echo "${m}Cloned repo to ${i}$dest_dir${n}"
   else
-    echo "Failed to clone repo!"
+    echo "${e}Failed to clone repo!${n}"
     exit 1
   fi
 fi
@@ -35,22 +39,22 @@ fi
 local conf="$HOME/.tmux.conf"
 if test -L $conf
 then
-  echo "Target '$conf' is symlink!"
-  echo "Removing symlink!"
+  echo "${m}Target '${i}$conf${m}' is symlink!${n}"
+  echo "${m}Removing symlink!${n}"
   rm $conf
 fi
 
 if test -f $conf
 then
-  echo "Target '$conf' already exists!"
-  echo "Created backup '$conf.bak'!"
+  echo "${m}Target '${i}$conf${m}' already exists!${n}"
+  echo "${m}Created backup '${i}$conf.bak${m}'!${n}"
   mv -b $conf $conf.backup
 fi
 
 local conf_new="$dest_dir/tmux.conf"
 if test -f $conf_new
 then
-  echo "Linking to '$conf_new' to '$conf'..."
+  echo "${m}Linking to '${i}$conf_new${m}' to '${i}$conf${m}'...${n}"
   ln -sf $conf_new $conf
 fi
 unset conf_new
@@ -60,7 +64,7 @@ if test -f $plugin_lst
 then
   mkdir -p $dest_dir/plugins &>/dev/null
 
-  echo "Reading plugin list..."
+  echo "${m}Reading plugin list...${n}"
   typeset -A plugins
   while read name url
   do
@@ -68,7 +72,7 @@ then
   done < $plugin_lst
   unset name url
 
-  echo "Fetching plugins..."
+  echo "${m}Fetching plugins...${n}"
   for dest url in ${(kv)plugins}
   do
     dest="$dest_dir/plugins/$dest"
@@ -83,9 +87,7 @@ fi
 tmux source $conf
 unset conf
 
-echo "Remember to install plugins (C^a-I)!"
-echo "Done!"
-
+echo "${m}Done${n}"
 exit 0
 
 # vim: ft=zsh ts=2 sw=2 et:
diff --git a/penguin-dev-tools/setup_vim b/penguin-dev-tools/setup_vim
--- a/penguin-dev-tools/setup_vim
+++ b/penguin-dev-tools/setup_vim
@@ -3,7 +3,7 @@
 # setup vim
 
 # source
-src_url="https://git.linuxit.us/spider/vim"
+src_url=${URL:-"https://git.linuxit.us/spider/vim"}
 tpo_url="https://tpo.pe/pathogen.vim"
 
 # install to
@@ -12,23 +12,27 @@ dest_dir="$HOME/.vim"
 # plugins
 plugin_lst="$dest_dir/plugins.txt"
 
-echo "Installing zsh setup..."
-echo "Source: $src_url"
-echo "Target: $dest_dir"
+# color output (msg,info,err,reset)
+m='\033[1;35m'; i='\033[1;32m'; e='\033[1;31m'; n='\033[0m'
 
-read -s -k "?Press any key continue" && echo
+echo "${m}Installing vim setup...${n}"
+echo "${m}Source: ${i}$src_url${n}"
+echo "${m}Target: ${i}$dest_dir${n}"
+echo "${i}"
+vared -cp "Confirm (y/n)? " ans
+[[ "$ans" =~ ^[Yy]$ ]] || exit 1
 
 # clone repo
 if test -d $dest_dir
 then
-  echo "Target '$dest_dir' already exists!"
+  echo "${e}Target '${i}$dest_dir${m}' already exists!${n}"
   exit 1
 else
   if git clone $src_url $dest_dir
   then
-    echo "Cloned repo to $dest_dir"
+    echo "${m}Cloned repo to ${i}$dest_dir${n}"
   else
-    echo "Failed to clone repo!"
+    echo "${e}Failed to clone repo!${n}"
     exit 1
   fi
 fi
@@ -36,27 +40,27 @@ fi
 local old_rc="$HOME/.vimrc"
 if test -L $old_rc
 then
-  echo "Target '$old_rc' is symlink!"
-  echo "Removing symlink!"
+  echo "${m}Target '${i}$old_rc${m}' is symlink!${n}"
+  echo "${m}Removing symlink!${n}"
   rm $conf
 fi
 
 if test -f $old_rc
 then
-  echo "Target '$old_rc' already exists!"
-  echo "Created backup '$old_rc.bak'!"
+  echo "${m}Target '${i}$old_rc${m}' already exists!${n}"
+  echo "${m}Created backup '${i}$old_rc.bak${m}'!${n}"
   mv -b $old_rc $old_rc.backup
 fi
 
 unset old_rc
 
-echo "Installing Pathogen..."
+echo "${m}Installing Pathogen...${n}"
 local bundle_dir="$dest_dir/bundle"
 local autoload_dir="$dest_dir/autoload"
 mkdir -p $autoload_dir $bundle_dir 2>/dev/null
 if ! curl -LSso $autoload_dir/$(basename "$tpo_url") $tpo_url
 then
-  echo "Failed to install Pathogen!"
+  echo "${e}Failed to install Pathogen!${n}"
   exit 1
 fi
 
@@ -65,7 +69,7 @@ if test -f $plugin_lst
 then
   mkdir -p $dest_dir/bundle &>/dev/null
 
-  echo "Reading plugin list..."
+  echo "Reading plugin list...${n}"
   typeset -A plugins
   while read name url
   do
@@ -73,7 +77,7 @@ then
   done < $plugin_lst
   unset name url
 
-  echo "Fetching plugins..."
+  echo "Fetching plugins...${n}"
   for dest url in ${(kv)plugins}
   do
     dest="$dest_dir/bundle/$dest"
@@ -85,7 +89,7 @@ then
   unset dest url
 fi
 
-echo "Done!"
+echo "${i}Done${n}"
 exit 0
 
 # vim: ft=zsh ts=2 sw=2 et:
diff --git a/penguin-dev-tools/setup_zsh b/penguin-dev-tools/setup_zsh
--- a/penguin-dev-tools/setup_zsh
+++ b/penguin-dev-tools/setup_zsh
@@ -3,7 +3,7 @@
 # setup zsh
 
 # source
-src_url="https://git.linuxit.us/spider/zsh"
+src_url=${URL:-"https://git.linuxit.us/spider/zsh"}
 
 # install to
 dest_dir="$HOME/.zsh"
@@ -11,23 +11,27 @@ dest_dir="$HOME/.zsh"
 # plugins
 plugin_lst="$dest_dir/plugins.txt"
 
-echo "Installing zsh setup..."
-echo "Source: $src_url"
-echo "Target: $dest_dir"
+# color output (msg,info,err,reset)
+m='\033[1;35m'; i='\033[1;32m'; e='\033[1;31m'; n='\033[0m'
 
-read -s -k "?Press any key continue" && echo
+echo "${m}Installing zsh setup...${n}"
+echo "${m}Source: ${i}$src_url${n}"
+echo "${m}Target: ${i}$dest_dir${n}"
+echo "${i}"
+vared -cp "Confirm (y/n)? " ans
+[[ "$ans" =~ ^[Yy]$ ]] || exit 1
 
 # clone repo
 if test -d $dest_dir
 then
-  echo "Target '$dest_dir' already exists!"
+  echo "${m}Target '${i}$dest_dir${m}' already exists!${n}"
   exit 1
 else
   if git clone $src_url $dest_dir
   then
-    echo "Cloned repo to $dest_dir"
+    echo "${m}Cloned repo to ${i}$dest_dir${n}"
   else
-    echo "Failed to clone repo!"
+    echo "${e}Failed to clone repo!${n}"
     exit 1
   fi
 fi
@@ -35,9 +39,9 @@ fi
 # link .zshenv to $HOME
 if test -f $HOME/.zshenv
 then
-  echo "Target '$HOME/.zshenv' already exists!"
+  echo "${m}Target '${i}$HOME/.zshenv${m}' already exists!${n}"
 else
-  echo "Linking to '$dest_dir/.zshenv'..."
+  echo "${m}Linking to '${i}$dest_dir/.zshenv${m}'...${n}"
   ln -sf $dest_dir/.zshenv $HOME/.zshenv
 fi
 
@@ -46,7 +50,7 @@ if test -f $plugin_lst
 then
   mkdir -p $dest_dir/plugins &>/dev/null
 
-  echo "Reading plugin list..."
+  echo "${m}Reading plugin list...${n}"
   typeset -A plugins
   while read name url
   do
@@ -54,9 +58,10 @@ then
   done < $plugin_lst
   unset name url
 
-  echo "Fetching plugins..."
+  echo "${m}Fetching plugins...${n}"
   for dest url in ${(kv)plugins}
   do
+    echo "${m}Cloning '${i}$dest${m}'...${n}"
     dest="$dest_dir/plugins/$dest"
     if ! test -d $dest
     then
@@ -66,7 +71,7 @@ then
   unset dest url
 fi
 
-echo "Done!"
+echo "${i}Done${n}"
 exit 0
 
 # vim: ft=zsh ts=2 sw=2 et:
